//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerPress
        {
            get
            {
                return SteamVR_Actions.default_TriggerPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadTouch
        {
            get
            {
                return SteamVR_Actions.default_TouchpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadNorth
        {
            get
            {
                return SteamVR_Actions.default_TouchpadNorth;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadSouth
        {
            get
            {
                return SteamVR_Actions.default_TouchpadSouth;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadEast
        {
            get
            {
                return SteamVR_Actions.default_TouchpadEast;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadWest
        {
            get
            {
                return SteamVR_Actions.default_TouchpadWest;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadTouchLocation
        {
            get
            {
                return SteamVR_Actions.default_TouchpadTouchLocation;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerPose
        {
            get
            {
                return SteamVR_Actions.default_TriggerPose;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripPress
        {
            get
            {
                return SteamVR_Actions.default_GripPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadClick
        {
            get
            {
                return SteamVR_Actions.default_TouchpadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuButtonClick
        {
            get
            {
                return SteamVR_Actions.default_MenuButtonClick;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
