//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_TriggerPress;
        
        private static SteamVR_Action_Boolean p_default_TouchpadTouch;
        
        private static SteamVR_Action_Boolean p_default_TouchpadNorth;
        
        private static SteamVR_Action_Boolean p_default_TouchpadSouth;
        
        private static SteamVR_Action_Boolean p_default_TouchpadEast;
        
        private static SteamVR_Action_Boolean p_default_TouchpadWest;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Vector2 p_default_TouchpadTouchLocation;
        
        private static SteamVR_Action_Single p_default_TriggerPose;
        
        private static SteamVR_Action_Boolean p_default_GripPress;
        
        private static SteamVR_Action_Boolean p_default_TouchpadClick;
        
        private static SteamVR_Action_Boolean p_default_MenuButtonClick;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        public static SteamVR_Action_Boolean default_TriggerPress
        {
            get
            {
                return SteamVR_Actions.p_default_TriggerPress.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TouchpadTouch
        {
            get
            {
                return SteamVR_Actions.p_default_TouchpadTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TouchpadNorth
        {
            get
            {
                return SteamVR_Actions.p_default_TouchpadNorth.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TouchpadSouth
        {
            get
            {
                return SteamVR_Actions.p_default_TouchpadSouth.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TouchpadEast
        {
            get
            {
                return SteamVR_Actions.p_default_TouchpadEast.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TouchpadWest
        {
            get
            {
                return SteamVR_Actions.p_default_TouchpadWest.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_TouchpadTouchLocation
        {
            get
            {
                return SteamVR_Actions.p_default_TouchpadTouchLocation.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single default_TriggerPose
        {
            get
            {
                return SteamVR_Actions.p_default_TriggerPose.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GripPress
        {
            get
            {
                return SteamVR_Actions.p_default_GripPress.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TouchpadClick
        {
            get
            {
                return SteamVR_Actions.p_default_TouchpadClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_MenuButtonClick
        {
            get
            {
                return SteamVR_Actions.p_default_MenuButtonClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_TriggerPress,
                    SteamVR_Actions.default_TouchpadTouch,
                    SteamVR_Actions.default_TouchpadNorth,
                    SteamVR_Actions.default_TouchpadSouth,
                    SteamVR_Actions.default_TouchpadEast,
                    SteamVR_Actions.default_TouchpadWest,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_TouchpadTouchLocation,
                    SteamVR_Actions.default_TriggerPose,
                    SteamVR_Actions.default_GripPress,
                    SteamVR_Actions.default_TouchpadClick,
                    SteamVR_Actions.default_MenuButtonClick,
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_TriggerPress,
                    SteamVR_Actions.default_TouchpadTouch,
                    SteamVR_Actions.default_TouchpadNorth,
                    SteamVR_Actions.default_TouchpadSouth,
                    SteamVR_Actions.default_TouchpadEast,
                    SteamVR_Actions.default_TouchpadWest,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_TouchpadTouchLocation,
                    SteamVR_Actions.default_TriggerPose,
                    SteamVR_Actions.default_GripPress,
                    SteamVR_Actions.default_TouchpadClick,
                    SteamVR_Actions.default_MenuButtonClick};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_TriggerPress,
                    SteamVR_Actions.default_TouchpadTouch,
                    SteamVR_Actions.default_TouchpadNorth,
                    SteamVR_Actions.default_TouchpadSouth,
                    SteamVR_Actions.default_TouchpadEast,
                    SteamVR_Actions.default_TouchpadWest,
                    SteamVR_Actions.default_GripPress,
                    SteamVR_Actions.default_TouchpadClick,
                    SteamVR_Actions.default_MenuButtonClick};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_TriggerPose};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_TouchpadTouchLocation};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_TriggerPress,
                    SteamVR_Actions.default_TouchpadTouch,
                    SteamVR_Actions.default_TouchpadNorth,
                    SteamVR_Actions.default_TouchpadSouth,
                    SteamVR_Actions.default_TouchpadEast,
                    SteamVR_Actions.default_TouchpadWest,
                    SteamVR_Actions.default_TouchpadTouchLocation,
                    SteamVR_Actions.default_TriggerPose,
                    SteamVR_Actions.default_GripPress,
                    SteamVR_Actions.default_TouchpadClick,
                    SteamVR_Actions.default_MenuButtonClick};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_TriggerPress = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TriggerPress")));
            SteamVR_Actions.p_default_TouchpadTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TouchpadTouch")));
            SteamVR_Actions.p_default_TouchpadNorth = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TouchpadNorth")));
            SteamVR_Actions.p_default_TouchpadSouth = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TouchpadSouth")));
            SteamVR_Actions.p_default_TouchpadEast = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TouchpadEast")));
            SteamVR_Actions.p_default_TouchpadWest = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TouchpadWest")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_TouchpadTouchLocation = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/TouchpadTouchLocation")));
            SteamVR_Actions.p_default_TriggerPose = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/TriggerPose")));
            SteamVR_Actions.p_default_GripPress = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GripPress")));
            SteamVR_Actions.p_default_TouchpadClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TouchpadClick")));
            SteamVR_Actions.p_default_MenuButtonClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/MenuButtonClick")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
        }
    }
}
